### ISSUE TITLE
Block Examples

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [LennardF1989/BF2042-Portal-Docs#3]
Think we can add a section on the docs for commonly used blocks such as getting players on a current team or getting all players that are alive, etc etc.

**Comment by LennardF1989** [comment]
Totally agree! I'll whip up a starting point and we can go from there :)

**Comment by LennardF1989** [comment]
Here you go! https://github.com/LennardF1989/BF2042-Portal-Docs/tree/master/docs/snippets
