### ISSUE TITLE
Wrong Url in Wait block in ClearAllCustomMessages

### ISSUE THREAD

**Issue by p0lygun** [LennardF1989/BF2042-Portal-Docs#9]
the `Wait` block url currently leads to a 404 on the website, its pointing to `docs/blocks/Wait.md`
[ClearAllCustomMessages.md#notes](https://github.com/LennardF1989/BF2042-Portal-Docs/blob/master/docs/blocks/ClearAllCustomMessages.md#notes)

**Comment by LennardF1989** [comment]
Thanks - the problem is the .md, I'll get rid of it :)
